### ISSUE TITLE
Struktur e-mail-Adresse, Website

### ISSUE THREAD

**Issue by oesterli** [swissgeol/dmAssets#12]
@signedav 
In der Klasse `Contact` sollen e-mail adressen und Websites und tel.Nr. abgebildet werden.

Diese sollten einer bestimmten Struktur entsprechen, z.B.: [Ziffern]. [Ziffern]@[Ziffern]. [Ziffern]
Wie kann man das definieren? Mit Regex, z.B.?

**Comment by signedav** [comment]
Enspricht eigentlich Matching Pattern Constrainst in PostgreSQL - dort sind Regular Expressions möglich. In Interlis hab ich das noch nie gemacht. Auch das werde ich abklären.
```
CREATE TABLE emails ( 
  email varchar CONSTRAINT proper_email CHECK (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
 );
```

**Comment by signedav** [comment]
Sieht nicht so aus, als ob es da was gäbe.

Nach erfolgloser Suche nach derartigen Constraints, hab ich mal bei einem kolumbianischen Kollegen nachgefragt. Dieser meinte:

> We face a similar issue,  unluckily there is no native support for pattern checking on interlis. Instead you can use two alternatives (external to an ili model)
>1. Create and implement a custom function for iliValidator, it requires define a new contracted model and then develop an ilivalidator-Java plug-in. (A first try was developed in Colombia)
>2.  Use a post-script on ili2db to create a custom constraint using sql.
>In both cases it requires an additional validation at user interface level, it means define manually the same constraint on qgis or the web application to avoid user mistakes.

**Comment by oesterli** [comment]
@signedav 
ok, dann macht es vielleicht mehr Sinn das im QGIS abzufangen. Das sollte Yves bei der Entwicklung des Plugins machen können. Oder was denkst Du?

**Comment by signedav** [comment]
Ja, es sei denn du möchtest den Typ `URI` verwenden. Ich denke der ist grösstenteils so wie in RFC https://datatracker.ietf.org/doc/html/rfc3986 spezifiziert umgesetzt. Dort bräuchtest du für die Email ein `mailto:`. Es wären dann aber auch sonstige URIs erlaubt.

**Comment by signedav** [comment]
Könnte man evtl. schon als Pseudo-Metaattribut notiert werden (Pseudo, weil es (noch) nicht von Model Baker oder so umgesetzt ist).
```
!!@contraintExpression="'^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'"
```
(wobei diese Expression nicht stimmt)

**Comment by nOester** [comment]
wir lassen es vorerst ohne definition von Metaattributen
