### ISSUE TITLE
Default Werte

### ISSUE THREAD

**Issue by oesterli** [swissgeol/dmAssets#34]
@signedav 
Kann man im INTERLIS-Modell "Defaultewrte" definieren? Oder ist das etwas, was man in der Applikation macht?

**Comment by signedav** [comment]
Noch nie gesehen - glaube nicht, dass das möglich ist im INTERLIS.

Was wir hier aber anwenden könnten wären **Meta-Attribute**. Meta-Attribute sind Informationen, die man im INTERLIS-Modell definiert, allerdings dann Applikationsabhängig sind, ob sie diese Informationen nutzen oder nicht. Das `ili2db` nutzt diese Attribute je nach dem, aber auf jeden Fall schreibt es sie in die Datenbank. Von dort aus können sie dann Applikationen wie der Model Baker oder auch das DmAsset-Erfasstool verwenden. Du erinnerst dich vielleicht an das Meta-Attribut `!!@ili2db.mapping=MultiPoint`, das wir mal in einer früheren Version hatten. Hier noch die Info zusammengefasst und auch eine Erläuterung des Meta-Attribut `dispExpression`, das von Model Baker verwendet wird. Ein Keyword `displayValueExpression` (oder ähnlich) existiert noch nicht, fände ich aber noch toll.

**Comment by signedav** [comment]
Dies ist übrigens etwas, dass man über die benutzung von UsabILIty Hub abdecken könnte. Dies bedarf keine Weiterentwicklung im Model Baker bzw. dem ILI Modell. Allerdings müsste das Projekt im UsabILIty Hub aufgesetzt werden. Das heisst, Style Layer sollen exportiert werden, Layertree in YAML geschrieben und das ilidata.xml auf dem Repo angepasst werden. Dabei könnte ich aber sicher helfen, damit man sich nicht in alles einlesen muss. Da UsabILIty Hub noch relativ neu ist, gibt es (noch) kein Tool, der dies erleichert.

**Comment by nOester** [comment]
@signedav
Behandelst du das Thema der Defaultwerte im Rahmen des UsabilityHubs?
Ich bin gearde beim Aufräumen und würde das Issue gerne schliessen

**Comment by signedav** [comment]
Ja. Das kann ich machen. Muss natürlich aber die Standardwerte wissen. Können wir aber auch in einem zweiten Schritt machen.
