### ISSUE TITLE
Constraints in Version 2

### ISSUE THREAD

**Issue by nOester** [swissgeol/dmAssets#59]
@signedav 

Ich habe hier die Constraints inkl Beschreibung herauskopiert, die im aktuellen  branch "work220306_on" eingefügt habe. Ich bin mir nicht sicher, ob die Contraints den Beschreibungen wirklich entsprechen. die Beschreibungen geben das wieder, was die Contraints einschränken sollen.

**DM GeolAssets_V2**  

**CLASS AssetItem**  
```
	 /** Wenn Kind == report, dann muss TitlePublic gesetzt sein.
	  */
      MANDATORY CONSTRAINT Kind->Reference->Name->LocalisedText->Text == "report" OR 
	  DEFINED (TitlePublic);

	  /** Wenn IsExtract gesetzt (es handelt sich dann um ein extrahiertes Objekt, z.B. Bohrprofil aus einem Bericht), dann darf Kind nicht "report" oder "package" sein. Sonst darf IsExtract nicht gesetzt sein.
	  */
	  MANDATORY CONSTRAINT IsExtract AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "report") OR 
	  NOT (IsExtract);

	  /** Wenn Format == Archiv (zip), dann muss Kind == Package sein
	  */
	  MANDATORY CONSTRAINT Kind->Reference->Name->LocalisedText->Text == "package" AND 
	  Format->Reference->Name-> LocalisedText->Text == "zip" OR 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Format->Reference->Name-> LocalisedText->Text == "zip");

	  /**FormatComposition darf nur ausgefüllt sein, wenn für das Format "zip" gewählt wurde
	  */
	  MANDATORY CONSTRAINT (DEFINED (FormatComposition->Reference->Name->LocalisedText->Text)) AND Format->Reference->Name->LocalisedText->Text == "zip" OR NOT (DEFINED (FormatComposition));

```  

**ASSOCIATION AssetItemMain_AssetItemPart**

```  
      /** Wenn das AssetPart ein Extrakt ist, darf es kein übergeordnetes AssetMain besitzen, da selber ein Extrakte ist.
       */
      MANDATORY CONSTRAINT AssetItemPart->IsExtract AND NOT (AssetItemMain->IsExtract);
	  /** Wenn das AssetPart ein Extrakt ist, muss das übergeordnete AssetMain das Kind == "report" haben oder es darf kein Extrakt sein und das übergeordnete AssetMain ist ein "package" 
	  */
	  MANDATORY CONSTRAINT (AssetItemPart->IsExtract AND AssetItemMain->Kind->Reference->Name->LocalisedText->Text =="report") OR 
	  NOT (AssetItemPart->IsExtract AND AssetItemMain->Kind->Reference->Name->LocalisedText->Text == "package");
```  

**DM LG_GeolAssets_V2**  

**STRUCTURE InternalUse**  
```  
	/** DateExpireIsInternalUse darf nur ausgefüllt werden, wenn IsInternalUse == True
	*/
    MANDATORY CONSTRAINT IsInternalUse OR DEFINED (DateExpireIsInternalUse); 

``` 

**STRUCTURE PublicUse**    

```  
	/** DateExpireIsInternalUse darf nur ausgefüllt werden, wenn IsInternalUse == True
	*/
    MANDATORY CONSTRAINT IsPublicUse OR DEFINED (DateExpireIsPublicUse);
```  

**CLASS LGAssetItem**

```  
	  /** Wenn IsInternalUse == False, dann muss IsPublicUse auch == False sein.
	  */
	  MANDATORY CONSTRAINT PublicUse->IsPublicUse AND InternalUse->IsInternalUse OR NOT (PublicUse->IsPublicUse) AND NOT (InternalUse->IsInternalUse);
	  /**
	  */
	  MANDATORY CONSTRAINT InternalUse->DateExpireIsInternalUse <= PublicUse->DateExpireIsPublicUse;
	  /** Wenn DateExpireIsPublicUse geetzt, dann muss auch DateExpireIsInternalUse gesetzt sein.
	  */
	  MANDATORY CONSTRAINT (DEFINED (PublicUse->DateExpireIsPublicUse)) AND (DEFINED (InternalUse->DateExpireIsInternalUse)) OR NOT (DEFINED (PublicUse->DateExpireIsPublicUse));
```

**Comment by signedav** [comment]
### **CLASS AssetItem**  
#### Wenn Kind == report, dann muss TitlePublic gesetzt sein
Dies dünkt mich falsch:

```
      MANDATORY CONSTRAINT Kind->Reference->Name->LocalisedText->Text == "report" OR 
	  DEFINED (TitlePublic);
```
Der Constraint definiert, dass es entweder ein Report sein soll, oder - wenn es kein Report ist - TitlePublic nicht gesetzt sein soll.

Es sollte eher das sein (kein Report oder - wenn es ein Report ist - TitlePublic).
```
      MANDATORY CONSTRAINT Kind->Reference->Name->LocalisedText->Text != "report" OR 
	  DEFINED (TitlePublic);
```

Hier ein Einschub. Es gibt eine Funktionalität, die ich selbst noch nicht oft gebraucht habe, aber genau in deinem Fall nützlich sein könnte. 

```
      SET CONSTRAINT WHERE Kind->Reference->Name->LocalisedText->Text == "report":
	  DEFINED (TitlePublic);
```

#### Wenn IsExtract gesetzt (es handelt sich dann um ein extrahiertes Objekt, z.B. Bohrprofil aus einem Bericht), dann darf Kind nicht "report" oder "package" sein. Sonst darf IsExtract nicht gesetzt sein.
```
	  MANDATORY CONSTRAINT IsExtract AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "report") OR 
	  NOT (IsExtract);
```
Ist meines Erachtens korrekt. Dennoch mit dem `WHERE` könnten wir es etwas schöner machen:
```
	  SET CONSTRAINT WHERE IsExtract:
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "report") 
```

#### Wenn Format == Archiv (zip), dann muss Kind == Package sein
Und wenn es ein Package ist, muss es auch ein zip sein? Das besagt die folgende Bedingung:
```
	  MANDATORY CONSTRAINT Kind->Reference->Name->LocalisedText->Text == "package" AND 
	  Format->Reference->Name-> LocalisedText->Text == "zip" OR 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Format->Reference->Name-> LocalisedText->Text == "zip");
```

```
	  SET CONSTRAINT WHERE Kind->Reference->Name->LocalisedText->Text == "package":
		  Format->Reference->Name-> LocalisedText->Text == "zip" 
	  SET CONSTRAINT WHERE Format->Reference->Name-> LocalisedText->Text == "zip":
	          Kind->Reference->Name->LocalisedText->Text == "package"
```
... ist aber nicht viel kürzer als deins...

#### FormatComposition darf nur ausgefüllt sein, wenn für das Format "zip" gewählt wurde
```
	  MANDATORY CONSTRAINT (DEFINED (FormatComposition->Reference->Name->LocalisedText->Text)) AND Format->Reference->Name->LocalisedText->Text == "zip" OR NOT (DEFINED (FormatComposition));
```
Dieser Constraint besagt, dass `FormatComposition` immer leer sein "darf". Auch bei Zip. Hauptsache nicht ausgefüllt bei etwas anderem als Zip.

Könnte man mit dem WHERE so machen:
```
	  SET CONSTRAINT WHERE DEFINED (FormatComposition):
	          Format->Reference->Name-> LocalisedText->Text == "zip"
```

### **ASSOCIATION AssetItemMain_AssetItemPart**
#### Wenn das AssetPart ein Extrakt ist, darf es kein übergeordnetes AssetMain besitzen, das selber ein Extrakt ist.
```
      MANDATORY CONSTRAINT AssetItemPart->IsExtract AND NOT (AssetItemMain->IsExtract);
```
Der Constraint sagt, dass AssetItemPart immer ein Extract sein muss. Das ist ja nicht immer der Fall. Wenn ein Extrakt kein Main sein darf, dann würde ich einfach schreiben:
```
      MANDATORY CONSTRAINT NOT (AssetItemMain->IsExtract);
```
Denn ein AssetItemPart muss ja kein Extrakt sein.

#### Wenn das AssetPart ein Extrakt ist, muss das übergeordnete AssetMain das Kind == "report" haben oder es darf kein Extrakt sein und das übergeordnete AssetMain ist ein "package" 
In der Klasse hast du sichergestellt, dass ein report und 
```  
	  MANDATORY CONSTRAINT (AssetItemPart->IsExtract AND AssetItemMain->Kind->Reference->Name->LocalisedText->Text =="report") OR 
	  NOT (AssetItemPart->IsExtract AND AssetItemMain->Kind->Reference->Name->LocalisedText->Text == "package");
```  
Korrekt. Oder:
```  
	  SET CONSTRAINT WHERE AssetItemPart->IsExtract:
	  AssetItemMain->Kind->Reference->Name->LocalisedText->Text =="report"
	  SET CONSTRAINT WHERE NOT( AssetItemPart->IsExtract):
	  AssetItemMain->Kind->Reference->Name->LocalisedText->Text == "package"
```
Grundsätzlich hast du damit eigentlich schon den ersten Constraint erfüllt. Denn hier wird definiert, dass so oder so der AssetItemMain ein report oder ein package sein muss. Also kann er kein IsExtract sein.

### STRUCTURE InternalUse**  
#### DateExpireIsInternalUse darf nur ausgefüllt werden, wenn IsInternalUse == True
Heisst, wenn IsInternalUse, darf aber Date auch nicht ausgefüllt sein, oder?
``` 
MANDATORY CONSTRAINT IsInternalUse OR DEFINED (DateExpireIsInternalUse); 
``` 
Der ist nicht korrekt. Das wär:
``` 
MANDATORY CONSTRAINT IsInternalUse AND DEFINED (DateExpireIsInternalUse) OR NOT(IsInternalUse); 
``` 
Oder mit WHERE:
```
SET CONSTRAINT WHERE DEFINED (DateExpireIsInternalUse):
  IsInternalUse
```
### STRUCTURE PublicUse 
#### DateExpireIsInternalUse darf nur ausgefüllt werden, wenn IsInternalUse == True
Meinst wahrscheinlich das gleiche wie oben aber mit IsPublicUse und DateExpireIsPublicUse.
--> gleiche Situation wie oben...

### CLASS LGAssetItem

#### Wenn IsInternalUse == False, dann muss IsPublicUse auch == False sein.
Und wenn es true ist? Muss das andere auch true sein? Ich denke schon, gemäss diesem hier:
```
	  MANDATORY CONSTRAINT PublicUse->IsPublicUse AND InternalUse->IsInternalUse OR NOT (PublicUse->IsPublicUse) AND NOT (InternalUse->IsInternalUse);
```
ist korrekt. Oder:
```
	  SET CONSTRAINT WHERE PublicUse->IsPublicUse OR InternalUse->IsInternalUse:
	     PublicUse->IsPublicUs AND InternalUse->IsInternalUse
```
ist aber bisschen abgekürzt. Vielleicht so verständlicher:
```
	  SET CONSTRAINT WHERE PublicUse->IsPublicUse:
	     InternalUse->IsInternalUse
	  
	  SET CONSTRAINT WHERE InternalUse->IsInternalUse:
	     PublicUse->IsPublicUs

```
#### PublicUse->DateExpireIsPublicUse muss grösser sein
```
MANDATORY CONSTRAINT InternalUse->DateExpireIsInternalUse <= PublicUse->DateExpireIsPublicUse;
```
Doch sie könnten ja beide nicht definiert sein. Wie wärs mit allem zusammen so:
```
	  SET CONSTRAINT WHERE PublicUse->IsPublicUse OR InternalUse->IsInternalUse:
	     PublicUse->IsPublicUs AND InternalUse->IsInternalUse AND
	     DEFINED (PublicUse->DateExpireIsPublicUse)) AND (DEFINED (InternalUse->DateExpireIsInternalUse) AND
	     InternalUse->DateExpireIsInternalUse <= PublicUse->DateExpireIsPublicUse
```
#### Wenn DateExpireIsPublicUse geetzt, dann muss auch DateExpireIsInternalUse gesetzt sein.
```
	  MANDATORY CONSTRAINT (DEFINED (PublicUse->DateExpireIsPublicUse)) AND (DEFINED (InternalUse->DateExpireIsInternalUse)) OR NOT (DEFINED (PublicUse->DateExpireIsPublicUse));
```
schein korrekt, aber wär auch oben abgedeckt.

**Comment by nOester** [comment]
@signedav 

Ich habe die Constraints eingebaut und mit ili2 geprüft.
Für [GeolAssets_V2.ili](https://github.com/swissgeol/dmAssets/blob/work220306_on/src/GeolAssets_V2.ili) ist alles gut.
für [LG_GeolAssets_V2.ili](https://github.com/swissgeol/dmAssets/blob/work220306_on/src/LG_GeolAssets_V2.ili) bekomme ich folgende Fehler:
```
M:\Appl\DATA\PROD\lg\01_PRODUKTION\Datenmodell\34-Unterstuetzung_tech_Modellierung\DM-Asset\work\dmAssets\src\LG_GeolAssets_V2.ili:72:There can not be a SET CONSTRAINT in a STRUCTURE LG_GeolAssets_V2.InternalUse.
M:\Appl\DATA\PROD\lg\01_PRODUKTION\Datenmodell\34-Unterstuetzung_tech_Modellierung\DM-Asset\work\dmAssets\src\LG_GeolAssets_V2.ili:95:There can not be a SET CONSTRAINT in a STRUCTURE LG_GeolAssets_V2.PublicUse.
M:\Appl\DATA\PROD\lg\01_PRODUKTION\Datenmodell\34-Unterstuetzung_tech_Modellierung\DM-Asset\work\dmAssets\src\LG_GeolAssets_V2.ili:253:Name IsPublicUselUse is not applicable to STRUCTURE LG_GeolAssets_V2.PublicUse.
M:\Appl\DATA\PROD\lg\01_PRODUKTION\Datenmodell\34-Unterstuetzung_tech_Modellierung\DM-Asset\work\dmAssets\src\LG_GeolAssets_V2.ili:253:logical expression required.
```

**Comment by signedav** [comment]
Letzteres ist ein Typo `IsPublicUselUse` statt `IsPublicUse`

**Comment by signedav** [comment]
Offenbar funktionieren die `SET CONSTRAINT` nicht in den `STRUCTURES`. Du könntest sie ohne `SET CONSTRAINT` machen oder in der Klasse überprüfen.

Ohne `SET`:

```
  MANDATORY CONSTRAINT NOT( DEFINED (DateExpireIsInternalUse)) OR NOT (IsInternalUse);
  
  MANDATORY CONSTRAINT NOT( DEFINED(DateExpireIsPublicUse)) OR NOT (IsPublicUse);
```

**Comment by signedav** [comment]
Habe eine Source für dieses Statement gesucht, dass SET CONSTRAINT nicht auf STRUCTURES funktionieren. Hab gerade nichts gefunden. Im Referenzhandbuch ist zwar schon nur von Klassen die Rede, aber es schliesst STRUCTURES nicht explizit aus. Aber STUCTURES sind ja schon speziell, da die Einträge nicht alleine existieren können (ohne von einem Objekt referenziert), deshalb kann vermutlich auch nicht eine Teilmenge daraus genommen werden.

Übrigens verwirrt mich ein Satz im Referenzhandbuch "Da sich solche Konsistenzbedingungen nicht auf das einzelne Objekt beziehen, können nie die Werte von Attributen angesprochen werden." Doch wir sprechen ja Werte von Attributen an (zBs. IsInternalUse) und das funktioniert auch so.

Sicher aber gut, wenn wir das ganze dann noch gut testen. Auch falls wir uns in einigen Constraint-Konstruktionen noch vertan haben.

**Comment by nOester** [comment]
@signedav 

Folgende offene Punkte zum GeolAssets_V2.ili sind noch mit @moojoel anzusehen und evtl. zu korrigieren
Hinweis: Nachfolgend genannte Zeilen-Nummern stimmen nicht mehr unbedingt i den aktuellen Files

- Frage: Constraint Zeile 91  : «Wenn Kind == report, TitlePublic muss gesetzt sein». Sowohl Kind als TitlePublic sind oben als Mandatory angegeben. Doppelt gemoppelt? 

- Anmerkung: Constraint Zeile 95: «Wenn IsExtract gesetzt, dann darf Kind nicht ‘report’ oder ‘package’ sein». Ich denke report darf es sein, da ja ein Packet (zip) mit mehreren Reports als package kommt, dann kann aber immer noch ein report erfasst werden, welcher dann ein extract aus package ist. Ich würde dies nur auf [..] darf nicht ‘package’ sein, einschränken.

- Anmerkung: Constraint Zeile 196: «Wenn das AssetPart ein Extrakt ist, muss das übergeordnete AssetMain das Kind == "report" haben oder es darf kein Extrakt sein und das übergeordnete AssetMain ist ein "package"». Ich denke, das übergeordnete AssetMain darf alles sein. Es kann sowohl ein Extrakt aus einem Package sein oder aus irgendetwas anderem. Es könnte ja auch ein Teil einer grossen Karten sein (Bild), oder Aussschnitt aus einem Log, Messreihe etc. Ich denke diesen Constraint kann weggelassen werden?

**Comment by signedav** [comment]
1: TitlePublic nicht MANDATORY / TitleOriginal MANDATORY / kein constraint auf "report" - denn reports benötigen nicht immer einen TitlePublic da sie nicht immer sensibel sind. TitleOriginal beschreibt den Asset und soll immer vorhanden sein.

2: Ein "Part" ist dann ein Extract, wenn er nicht Teil eines Package ist, sondern von sonst etwas (zBs. report).
Das heisst es gibt die Hierarchie:
```
- Package (Main)
  |- Asset (Part und Main aber nicht Extract)
     |- Asset (Part und Extract)
     |- Asset (Part und Extract)
     |- Asset (Part und Extract)
  |- Asset (Part und Main aber nicht Extract)
     |- Asset (Part und Extract)
     |- Asset (Part und Extract)
```
oder:
```
|- Asset (Main)
   |- Asset (Part und Extract)
   |- Asset (Part und Extract)
   |- Asset (Part und Extract)
```
Also stimmen die Contstraints hier.

3. Einverstanden, es kann alles sein.
Wir müssen sicherstellen, dass ein Main nicht ein Extract ist. Das machen wir im Moment so dass 1. wir prüfen dass ein Extract nie ein Package oder Report ist und ein Main entweder ein Package oder ein Report ist.
In der Class:
```
	  SET CONSTRAINT WHERE IsExtract: 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "package") AND 
	  NOT (Kind->Reference->Name->LocalisedText->Text == "report");
```
In der Association:
```
	  SET CONSTRAINT WHERE AssetItemPart->IsExtract: 
	  AssetItemMain->Kind->Reference->Name->LocalisedText->Text =="report";
	  SET CONSTRAINT WHERE NOT( AssetItemPart->IsExtract): 
	  AssetItemMain->Kind->Reference->Name->LocalisedText->Text == "package";
```

**Comment by signedav** [comment]
```
	  SET CONSTRAINT WHERE AssetItemPart->IsExtract: 
	  NOT(AssetItemMain->IsExtract);
	  SET CONSTRAINT WHERE NOT( AssetItemPart->IsExtract): 
	  AssetItemMain->Kind->Reference->Name->LocalisedText->Text == "package" AND 
NOT(AssetItemPart->Kind->Reference->Name->LocalisedText->Text == "package");
;
```
