### ISSUE TITLE
QGIS - Change "NULL-Werte erlaben"

### ISSUE THREAD

**Issue by nOester** [swissgeol/dmAssets#66]
@signedav 
Kann man für mehrere Layer gleichzeit ändern, dass für verschiedene attribute NULL-Werte erlaubt sind.

Zum Beispiel muss man, wenn man neue Werte in einer Domain erfasst, für die "parent..."-Attribute NULL-Werte erlaube. Sonst wird dort irgendein Wert automatisch zugewiesen.
Ich schalte jetzt für jedes "parent..."-Attribut in den Formulareigenschaften "NULL-Werte erlauben" manuell ein. Das ist sehr aufwändig.

Kann man das xml des QGIS-Projekte anpassen, so wie man auch den Schreibschutz der Domänen ausschalten kann?

![image](https://user-images.githubusercontent.com/51328443/160109700-d19e2cf7-1310-4d61-8d9d-8b11944f0285.png)

**Comment by signedav** [comment]
Ich weiss gerade keine schnelle Lösung dafür. Eigentlich sollte Model Baker diesen Wert setzen. Kann aber sein, dass ers für diese Layer nicht tut, da sie sowieso nicht für die Bearbeitung gedacht sind. 

Im XML der QGS Datei denke ich, kannst du den Wert nicht setze, da die Konfiguration gar nicht gespeicher wurde, sondern anhand der Relation erkannt wird.
