### ISSUE TITLE
CatalogueItem durch MandatoryCatalogueItem ersetzen

### ISSUE THREAD

**Issue by nOester** [swissgeol/dmAssets#68]
Nach Feedback von Rolf Z. zum DM Profile soll in den Katalog-Modellen die STRUCTURE `CatalogueItem` durch `MandatoryCatalogueitem` ersetzt werden

**Comment by signedav** [comment]
Geht es um `CatalogueReference` und `MandatoryCatalogueReference`? Ja, das ist gut. Hatte irgenwie im Kopf, dass wir das schon hatten. Denn aufgrund der Modelierung von DmAssets und DmFaults ist mir dieser Issue (ili2db/QgisModelBaker) aufgefallen https://github.com/opengisch/QgisModelBaker/issues/623
