### ISSUE TITLE
Constraints auf Text statt auf Code

### ISSUE THREAD

**Issue by signedav** [swissgeol/dmAssets#71]
Hier werden noch immer Checks auf den Text gemacht. Ist das Absicht?

https://github.com/swissgeol/dmAssets/blob/main/src/GeolAssets_V2.ili#L109-L115

Ansonsten wärs so:
```
	  /** FormatComposition darf nur ausgefüllt sein, wenn für das Format "zip" gewählt wurde
	  */
	  SET CONSTRAINT WHERE DEFINED (FormatComposition): 
	  Format->Reference->Code == "zip";

	  /** Wenn FormatComposition ausgefüllt ist, muss für das Format "zip" gewählt werden
	  */
	  SET CONSTRAINT WHERE Format->Reference->Code == "zip": 
	  DEFINED (FormatComposition);
```

Und das "könnten" wir auch zusammen mit den package checks machen. Wenn es allerding thematisch getrennt sein soll, ist das so auch in Ordnung für mich.

**Comment by signedav** [comment]
@oesterli

**Comment by nOester** [comment]
Hab's angepasst!
