### ISSUE TITLE
Extended TOPIC und gleichnamige abgeleitete Klassen

### ISSUE THREAD

**Issue by signedav** [swissgeol/dmAssets#72]
Ich denke wir müssen das Topic extenden, damit wir bei einem Export die Elemente des Parent Topics mitkriegen. So:
```
TOPIC LGGeolAssets EXTENDS GeolAssets_V2.CoreGeolAsset, =
```

Evtl. könnten wir das Topic und die Klassen gleichnamig ableiten.

Etwa so:
```
TOPIC CoreGeolAssets EXTENDS GeolAssets_V2.CoreGeolAsset, =
  DEPENDS ON LG_GeolAssetsCatalogues_V2.Catalogues; 
  CLASS Contact (EXTENDED) = 
  [...]
  CLASS AssetItem (EXTENDED) =
  [...]
```

Und evtl. `CoreGeolAssets` zu `GeolAssets` umbenennen. 

Dies ist einerseits so wie ich es von Beginn her gemacht hätte, wenn wir gar nie auf die Base / Package etc. Versionen gekommen wären.
Vorteil allerdings der aktuellen Implementierung ist, dass man immer weiss, ob es sich um die Ableitung oder die "Originalklasse" handelt.

Vielleicht hast du @oesterli oder jemand deiner Leute eine Meinung dazu. Ich werde bis Donnerstag auch noch einige Abklärungen machen diesbezüglich.

**Comment by signedav** [comment]
Wie auch immer. Die Namen sind nicht so wichtig, wohl aber das EXTENDED Topic.

**Comment by nOester** [comment]
@signedav 
Fragen zu den oben genannten Punkten:
- Wenn wir da Topic erweiteren, muss man bei den erweitereten Klassen immer noch das `EXTENDS` bei behalten? Zum Beispiel: 
```
  TOPIC LGGeolAsset 
    EXTENDS GeolAssets_V2.CoreGeolAssets, =
    OID AS INTERLIS.UUIDOID;
    DEPENDS ON GeolAssets_V2.CoreGeolAssets,LG_GeolAssetsCatalogues_V2.Catalogues;

    CLASS LGContact (EXTENDED)
    EXTENDS GeolAssets_V2.CoreGeolAssets.Contact =
      IDZAD : TEXT;
    END LGContact;
```
- Warum sollte man die Topics und Klassen gleich benennen?
-

**Comment by nOester** [comment]
Hi @signedav 
Ich bekomme einen Fehler bei der Prüfung von LG_GeolAssets_V2.ili, wenn ich die Namen der Topics in beiden Modellen auf `GeolAssets` und die Namen der Klassen auf `AssetItemn`und `Contact`setzte.

Hier die Fehler Meldung:
```
src\LG_GeolAssets_V2.ili:284:CLASS LG_GeolAssets_V2.GeolAssets.Contact can not extend CLASS GeolAssets_V2.GeolAssets.Contact without changing its name.  TOPIC LG_GeolAssets_V2.GeolAssets extends TOPIC GeolAssets_V2.GeolAssets.
  CLASS LG_GeolAssets_V2.GeolAssets.Contact can not extend CLASS GeolAssets_V2.GeolAssets.Contact without changing its name.  TOPIC LG_GeolAssets_V2.GeolAssets extends TOPIC GeolAssets_V2.GeolAssets.
```

Kannst Du due das man ansehen, Ich komme sonst nicht weiter mit der Überführung der `UsedBy`-Struktur in eine Klasse.

Die files habe ich nochmal gepushed hier der Link zum commit https://github.com/swissgeol/dmAssets/pull/70/commits/c18863491c95bf13081163e7e0cadb85f1db8122
