### ISSUE TITLE
Review pre-release v2.0.0

### ISSUE THREAD

**Issue by nOester** [swissgeol/dmAssets#86]
@signedav 
Hallo Dave

Könntest Du einen Blick auf den Pre-Release  von V2.0.0 https://github.com/swissgeol/dmAssets/releases/tag/v2.0.0 werfen.

Die Change-log ist nicht sehr aussagekräftig aber man sich die Differenz anzeigen lassen. Wenn der Pre-Release für dich ok ist, werde ich ich offiziell releassen.

Danke und Gruss

Nils

**Comment by signedav** [comment]
Habs mir nochmals angeschaut. Sieht gut aus. Konnte es auch nochmals einspielen und mit meinem aktuellen QGIS Projekt arbeiten.

**Comment by nOester** [comment]
tipptopp! vielen Dank!
Dann werde ich den Release offiziell machen.
